export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const OPERATION_STATUS = 'OPERATION_STATUS';
export const GENERIC_STATUS = 'GENERIC_STATUS';
export const DISMISS_STATUS = 'DISMISS_STATUS';

export const USER_PROFILE_LOADING = 'USER_PROFILE_LOADING';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_ERROR = 'USER_PROFILE_ERROR';


export const ACHIEVEMENT_LIST_LOADING = 'ACHIEVEMENT_LIST_LOADING';
export const ACHIEVEMENT_LIST_SUCCESS = 'ACHIEVEMENT_LIST_SUCCESS';
export const ACHIEVEMENT_LIST_ERROR = 'ACHIEVEMENT_LIST_ERROR';
